//
// GenModelMetamodelExpectations.swift
// GenModelTests
//
//  Copyright © 2026 Rene Hexel. All rights reserved.
//

/// Expected structure of the generator metamodel, as the interface that `.genmodel` files rely on.
///
/// Feature rows use the layout `Class|kind|type|lower|upper|flags|default|opposite`, where
/// `kind` is `A` (attribute) or `R` (reference), flags are `C` containment, `N` not changeable,
/// `V` volatile, `T` transient, `U` unsettable, `D` derived and `P` proxies not resolved, and a
/// default of `-` means none and `~` means the empty string.
enum GenModelMetamodelExpectations {
    /// Class name, comma-separated supertypes, abstract flag, in metamodel order.
    static let classes: [(name: String, supertypes: String, isAbstract: Bool)] = [
        ("GenModel", "GenBase", false),
        ("GenPackage", "GenBase", false),
        ("GenClass", "GenClassifier", false),
        ("GenFeature", "GenTypedElement", false),
        ("GenBase", "", true),
        ("GenEnum", "GenDataType", false),
        ("GenEnumLiteral", "GenBase", false),
        ("GenClassifier", "GenBase", true),
        ("GenDataType", "GenClassifier", false),
        ("GenOperation", "GenTypedElement", false),
        ("GenParameter", "GenTypedElement", false),
        ("GenTypedElement", "GenBase", true),
        ("GenAnnotation", "GenBase", false),
        ("GenTypeParameter", "GenBase", false)
    ]

    /// Enumeration name and literals as (name, value, literal text).
    static let enums: [(name: String, literals: [(name: String, value: Int, literal: String)])] = [
        ("GenProviderKind", [("Singleton", 0, "Singleton"), ("Stateful", 1, "Stateful"), ("None", 2, "None")]),
        ("GenPropertyKind", [("Editable", 0, "Editable"), ("Readonly", 1, "Readonly"), ("None", 2, "None")]),
        ("GenResourceKind", [("None", 0, "None"), ("Basic", 1, "Basic"), ("XMI", 2, "XMI"), ("XML", 3, "XML")]),
        ("GenDelegationKind", [("None", 0, "None"), ("Reflective", 1, "Reflective"), ("Virtual", 2, "Virtual"), ("Dynamic", 3, "Dynamic")]),
        ("GenJDKLevel", [("JDK14", 0, "1.4"), ("JDK50", 1, "5.0"), ("JDK60", 2, "6.0"), ("JDK70", 3, "7.0"), ("JDK80", 4, "8.0"), ("JDK90", 5, "9.0"), ("JDK100", 6, "10.0"), ("JDK110", 7, "11.0"), ("JDK120", 8, "12.0"), ("JDK130", 9, "13.0"), ("JDK140", 10, "14.0"), ("JDK150", 11, "15.0"), ("JDK160", 12, "16.0"), ("JDK170", 13, "17.0"), ("JDK180", 14, "18.0"), ("JDK190", 15, "19.0"), ("JDK200", 16, "20.0"), ("JDK210", 17, "21.0"), ("JDK220", 18, "22.0"), ("JDK230", 19, "23.0"), ("JDK240", 20, "24.0"), ("JDK250", 21, "25.0"), ("JDK260", 22, "26.0"), ("JDK270", 23, "27.0")]),
        ("GenRuntimeVersion", [("EMF22", 0, "2.2"), ("EMF23", 1, "2.3"), ("EMF24", 2, "2.4"), ("EMF25", 3, "2.5"), ("EMF26", 4, "2.6"), ("EMF27", 5, "2.7"), ("EMF28", 6, "2.8"), ("EMF29", 7, "2.9"), ("EMF210", 8, "2.10"), ("EMF211", 9, "2.11"), ("EMF212", 10, "2.12"), ("EMF213", 11, "2.13"), ("EMF214", 12, "2.14"), ("EMF215", 13, "2.15"), ("EMF216", 14, "2.16"), ("EMF217", 15, "2.17"), ("EMF218", 16, "2.18"), ("EMF219", 17, "2.19"), ("EMF220", 18, "2.20"), ("EMF221", 19, "2.21"), ("EMF222", 20, "2.22"), ("EMF223", 21, "2.23"), ("EMF224", 22, "2.24"), ("EMF225", 23, "2.25"), ("EMF226", 24, "2.26"), ("EMF227", 25, "2.27"), ("EMF228", 26, "2.28"), ("EMF229", 27, "2.29"), ("EMF230", 28, "2.30"), ("EMF231", 29, "2.31"), ("EMF232", 30, "2.32"), ("EMF233", 31, "2.33"), ("EMF234", 32, "2.34"), ("EMF235", 33, "2.35"), ("EMF236", 34, "2.36"), ("EMF237", 35, "2.37"), ("EMF238", 36, "2.38"), ("EMF239", 37, "2.39"), ("EMF240", 38, "2.40"), ("EMF241", 39, "2.41"), ("EMF242", 40, "2.42"), ("EMF243", 41, "2.43"), ("EMF244", 42, "2.44"), ("EMF245", 43, "2.45")]),
        ("GenRuntimePlatform", [("IDE", 0, "IDE"), ("RCP", 1, "RCP"), ("RAP", 2, "RAP"), ("GWT", 3, "GWT")]),
        ("GenDecoration", [("None", 0, "None"), ("Manual", 1, "Manual"), ("Live", 2, "Live")]),
        ("GenEclipsePlatformVersion", [("Juno", 0, "Juno"), ("Kepler", 1, "Kepler"), ("Luna", 2, "Luna"), ("Mars", 3, "Mars"), ("Neon", 4, "Neon"), ("Oxygen", 5, "Oxygen"), ("Photon", 6, "Photon"), ("Eclipse_2018_09", 7, "2018-09"), ("Eclipse_2018_12", 8, "2018-12"), ("Eclipse_2019_03", 9, "2019-03"), ("Eclipse_2019_06", 10, "2019-06"), ("Eclipse_2019_09", 11, "2019-09"), ("Eclipse_2019_12", 12, "2019-12"), ("Eclipse_2020_03", 13, "2020-03"), ("Eclipse_2020_06", 14, "2020-06"), ("Eclipse_2020_09", 15, "2020-09"), ("Eclipse_2020_12", 16, "2020-12"), ("Eclipse_2021_03", 17, "2021-03"), ("Eclipse_2021_06", 18, "2021-06"), ("Eclipse_2021_09", 19, "2021-09"), ("Eclipse_2021_12", 20, "2021-12"), ("Eclipse_2022_03", 21, "2022-03"), ("Eclipse_2022_06", 22, "2022-06"), ("Eclipse_2022_09", 23, "2022-09"), ("Eclipse_2022_12", 24, "2022-12"), ("Eclipse_2023_03", 25, "2023-03"), ("Eclipse_2023_06", 26, "2023-06"), ("Eclipse_2023_09", 27, "2023-09"), ("Eclipse_2023_12", 28, "2023-12"), ("Eclipse_2024_03", 29, "2024-03"), ("Eclipse_2024_06", 30, "2024-06"), ("Eclipse_2024_09", 31, "2024-09"), ("Eclipse_2024_12", 32, "2024-12"), ("Eclipse_2025_03", 33, "2025-03"), ("Eclipse_2025_06", 34, "2025-06"), ("Eclipse_2025_09", 35, "2025-09"), ("Eclipse_2025_12", 36, "2025-12"), ("Eclipse_2026_03", 37, "2026-03")]),
        ("GenCodeStyle", [("UnnecessaryElse", 0, "UnnecessaryElse"), ("SwitchMissingDefaultCase", 1, "SwitchMissingDefaultCase"), ("UnnecessaryAssignmentBeforeReturn", 2, "UnnecessaryAssignmentBeforeReturn"), ("UnnecessaryDeprecatedMethod", 3, "UnnecessaryDeprecatedMethod")]),
        ("GenOSGiStyle", [("ProvideCapabilityGeneratedPackage", 0, "ProvideCapabilityGeneratedPackage")])
    ]

    /// Data type name and instance type name.
    static let dataTypes: [(name: String, instanceType: String)] = [
        ("Path", "java.lang.String"),
        ("PropertyEditorFactory", "java.lang.String")
    ]

    /// One row per structural feature, in metamodel order.
    static let featureRows: [String] = [
        "GenModel|A|ecore.EString|0|1|-|-|-",
        "GenModel|A|Path|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|true|-",
        "GenModel|A|ecore.EBoolean|0|1|-|true|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|Path|0|1|U|-|-",
        "GenModel|A|Path|0|1|U|-|-",
        "GenModel|A|ecore.EString|0|1|-|-|-",
        "GenModel|A|ecore.EString|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EString|0|-1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EString|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EString|0|1|-|-|-",
        "GenModel|A|ecore.EString|0|1|-|-|-",
        "GenModel|A|ecore.EString|0|1|-|-|-",
        "GenModel|A|ecore.EString|0|1|U|-|-",
        "GenModel|A|ecore.EString|0|1|U|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|true|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|false|-",
        "GenModel|A|ecore.EString|0|-1|-|-|-",
        "GenModel|A|ecore.EString|0|-1|-|-|-",
        "GenModel|A|ecore.EString|0|1|-|org.eclipse.emf.ecore.EObject|-",
        "GenModel|A|ecore.EString|0|1|-|org.eclipse.emf.ecore.impl.EObjectImpl|-",
        "GenModel|A|ecore.EString|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EString|0|1|-|-|-",
        "GenModel|A|ecore.EString|0|1|-|-|-",
        "GenModel|A|ecore.EString|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|VTD|-|-",
        "GenModel|A|ecore.EBoolean|0|1|VD|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|Path|0|1|U|-|-",
        "GenModel|A|ecore.EString|0|1|U|-|-",
        "GenModel|A|ecore.EString|0|1|-|-|-",
        "GenModel|A|ecore.EInt|0|1|-|-1|-",
        "GenModel|A|ecore.EString|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|true|-",
        "GenModel|A|GenDelegationKind|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|true|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EString|0|1|-|org.eclipse.emf.codegen.merge.java.facade.ast.ASTFacadeHelper|-",
        "GenModel|A|GenJDKLevel|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|true|-",
        "GenModel|A|ecore.EBoolean|0|1|-|true|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EString|0|-1|-|-|-",
        "GenModel|A|ecore.EString|0|1|-|-|-",
        "GenModel|A|ecore.EString|0|1|-|-|-",
        "GenModel|A|ecore.EString|0|-1|-|-|-",
        "GenModel|A|ecore.EString|0|1|-|-|-",
        "GenModel|A|ecore.EString|0|-1|-|-|-",
        "GenModel|A|ecore.EString|0|1|-|-|-",
        "GenModel|A|ecore.EString|0|-1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|GenRuntimeVersion|0|1|U|-|-",
        "GenModel|A|ecore.EString|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|R|GenPackage|0|-1|C|-|GenPackage/genModel",
        "GenModel|R|GenPackage|0|-1|-|-|-",
        "GenModel|A|ecore.EString|0|1|-|-|-",
        "GenModel|A|ecore.EString|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|false|-",
        "GenModel|A|ecore.EBoolean|0|1|VTD|-|-",
        "GenModel|A|GenRuntimePlatform|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EString|0|1|-|-|-",
        "GenModel|A|GenDecoration|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|GenEclipsePlatformVersion|0|1|U|-|-",
        "GenModel|A|ecore.EString|0|1|U|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EInt|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|ecore.EBoolean|0|1|-|-|-",
        "GenModel|A|GenCodeStyle|0|-1|-|-|-",
        "GenModel|A|GenOSGiStyle|0|-1|-|-|-",
        "GenPackage|A|ecore.EString|0|1|-|-|-",
        "GenPackage|A|ecore.EString|0|1|-|-|-",
        "GenPackage|A|GenResourceKind|0|1|-|-|-",
        "GenPackage|A|ecore.EBoolean|0|1|-|-|-",
        "GenPackage|A|ecore.EBoolean|0|1|-|true|-",
        "GenPackage|A|ecore.EBoolean|0|1|-|-|-",
        "GenPackage|A|ecore.EString|0|1|-|~|-",
        "GenPackage|A|ecore.EString|0|1|-|~|-",
        "GenPackage|A|ecore.EString|0|1|-|impl|-",
        "GenPackage|A|ecore.EString|0|1|-|util|-",
        "GenPackage|A|ecore.EString|0|1|-|provider|-",
        "GenPackage|A|ecore.EString|0|1|-|presentation|-",
        "GenPackage|A|ecore.EString|0|1|-|tests|-",
        "GenPackage|A|ecore.EBoolean|0|1|-|true|-",
        "GenPackage|A|ecore.EBoolean|0|1|-|true|-",
        "GenPackage|A|ecore.EBoolean|0|1|-|-|-",
        "GenPackage|A|ecore.EBoolean|0|1|-|true|-",
        "GenPackage|A|ecore.EBoolean|0|1|-|true|-",
        "GenPackage|A|ecore.EBoolean|0|1|-|-|-",
        "GenPackage|A|ecore.EBoolean|0|1|-|-|-",
        "GenPackage|A|ecore.EString|0|1|-|-|-",
        "GenPackage|A|ecore.EString|0|1|-|-|-",
        "GenPackage|R|ecore.EPackage|1|1|-|-|-",
        "GenPackage|R|GenModel|0|1|T|-|GenModel/genPackages",
        "GenPackage|R|GenEnum|0|-1|C|-|-",
        "GenPackage|R|GenDataType|0|-1|C|-|-",
        "GenPackage|R|GenClass|0|-1|C|-|-",
        "GenPackage|R|GenPackage|0|-1|C|-|-",
        "GenPackage|R|GenClassifier|0|-1|NVTP|-|GenClassifier/genPackage",
        "GenPackage|A|ecore.EString|0|1|-|-|-",
        "GenPackage|A|ecore.EString|0|1|U|-|-",
        "GenPackage|A|ecore.EString|0|1|-|ecore|-",
        "GenPackage|A|ecore.EBoolean|0|1|-|-|-",
        "GenClass|A|GenProviderKind|0|1|-|-|-",
        "GenClass|A|ecore.EBoolean|0|1|-|true|-",
        "GenClass|A|ecore.EBoolean|0|1|-|-|-",
        "GenClass|R|ecore.EClass|1|1|-|-|-",
        "GenClass|R|GenFeature|0|-1|C|-|GenFeature/genClass",
        "GenClass|R|GenOperation|0|-1|C|-|GenOperation/genClass",
        "GenClass|R|GenFeature|0|1|-|-|-",
        "GenFeature|A|GenPropertyKind|0|1|-|-|-",
        "GenFeature|A|ecore.EBoolean|0|1|-|true|-",
        "GenFeature|A|ecore.EBoolean|0|1|-|-|-",
        "GenFeature|A|ecore.EBoolean|0|1|U|-|-",
        "GenFeature|A|ecore.EString|0|1|-|-|-",
        "GenFeature|A|ecore.EString|0|-1|-|-|-",
        "GenFeature|A|ecore.EString|0|1|-|-|-",
        "GenFeature|A|ecore.EBoolean|0|1|-|-|-",
        "GenFeature|A|ecore.EBoolean|0|1|-|-|-",
        "GenFeature|R|GenClass|1|1|T|-|GenClass/genFeatures",
        "GenFeature|R|ecore.EStructuralFeature|1|1|-|-|-",
        "GenFeature|A|ecore.EBoolean|0|1|U|-|-",
        "GenFeature|A|ecore.EBoolean|0|1|U|-|-",
        "GenFeature|A|ecore.EBoolean|0|1|U|-|-",
        "GenFeature|A|ecore.EBoolean|0|1|U|-|-",
        "GenFeature|A|ecore.EString|0|1|U|-|-",
        "GenFeature|A|PropertyEditorFactory|0|1|U|-|-",
        "GenBase|R|GenAnnotation|0|-1|C|-|GenAnnotation/genBase",
        "GenEnum|A|ecore.EBoolean|0|1|-|true|-",
        "GenEnum|R|ecore.EEnum|1|1|-|-|-",
        "GenEnum|R|GenEnumLiteral|0|-1|C|-|GenEnumLiteral/genEnum",
        "GenEnumLiteral|R|GenEnum|1|1|T|-|GenEnum/genEnumLiterals",
        "GenEnumLiteral|R|ecore.EEnumLiteral|1|1|-|-|-",
        "GenEnumLiteral|A|ecore.EString|0|1|U|-|-",
        "GenClassifier|R|GenPackage|1|1|NVTP|-|GenPackage/genClassifiers",
        "GenClassifier|R|GenTypeParameter|0|-1|C|-|-",
        "GenClassifier|A|ecore.EString|0|1|U|-|-",
        "GenDataType|R|ecore.EDataType|1|1|-|-|-",
        "GenDataType|A|ecore.EString|0|1|U|-|-",
        "GenDataType|A|ecore.EString|0|1|U|-|-",
        "GenDataType|A|PropertyEditorFactory|0|1|U|-|-",
        "GenOperation|R|GenClass|1|1|T|-|GenClass/genOperations",
        "GenOperation|R|ecore.EOperation|1|1|-|-|-",
        "GenOperation|R|GenParameter|0|-1|C|-|GenParameter/genOperation",
        "GenOperation|R|GenTypeParameter|0|-1|C|-|-",
        "GenOperation|A|ecore.EBoolean|0|1|U|-|-",
        "GenOperation|A|ecore.EString|0|1|U|-|-",
        "GenParameter|R|GenOperation|1|1|T|-|GenOperation/genParameters",
        "GenParameter|R|ecore.EParameter|1|1|-|-|-",
        "GenTypedElement|A|ecore.EString|0|1|U|-|-",
        "GenAnnotation|A|ecore.EString|0|1|-|-|-",
        "GenAnnotation|R|ecore.EStringToStringMapEntry|0|-1|CP|-|-",
        "GenAnnotation|R|GenBase|0|1|T|-|GenBase/genAnnotations",
        "GenAnnotation|R|ecore.EObject|0|-1|-|-|-",
        "GenAnnotation|R|ecore.EObject|0|-1|C|-|-",
        "GenTypeParameter|R|ecore.ETypeParameter|1|1|-|-|-",
        "GenTypeParameter|A|ecore.EString|0|1|U|-|-"
    ]
}
