<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="library" nsURI="http://example.org/fidelity/library" nsPrefix="lib">
  <eClassifiers xsi:type="ecore:EClass" name="Named" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lendable" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="loanDays" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="14"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onLoan" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eOperations name="borrow" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        eExceptions="#//LoanFailure">
      <eParameters name="days" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="notes" upperBound="-1" unique="false" ordered="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="giveBack"/>
    <eOperations name="holder" eType="#//Writer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Book" eSuperTypes="#//Named #//Lendable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pages" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="100"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="#//BookCategory" defaultValueLiteral="Mystery"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isbn" eType="#//ISBN"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="#//Path"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shelf" eType="#//catalogue/Shelf"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tags" upperBound="-1" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subtitle" unsettable="true"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" lowerBound="1" eType="#//Writer" eOpposite="#//Writer/books"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="library" eType="#//Library" eOpposite="#//Library/books"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="related" upperBound="-1" ordered="false" unique="false"
        resolveProxies="false" eType="#//Book"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaclass" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Writer" eSuperTypes="#//Named">
    <eStructuralFeatures xsi:type="ecore:EReference" name="books" upperBound="-1" eType="#//Book" eOpposite="#//Book/author"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Library" eSuperTypes="#//Named">
    <eStructuralFeatures xsi:type="ecore:EReference" name="books" upperBound="-1" containment="true" eType="#//Book"
        eOpposite="#//Book/library"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" upperBound="-1" containment="true" eType="#//StringToBookEntry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sections" upperBound="-1" containment="true" eType="#//catalogue/Section"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringToBookEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Book"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoanFailure" eSuperTypes="#//Named"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BookCategory">
    <eLiterals name="Fiction"/>
    <eLiterals name="Mystery" value="1" literal="MYSTERY"/>
    <eLiterals name="Biography" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ISBN" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Path" instanceClassName="java.nio.file.Path" serializable="false"/>
  <eSubpackages name="catalogue" nsURI="http://example.org/fidelity/library/catalogue" nsPrefix="cat">
    <eClassifiers xsi:type="ecore:EEnum" name="Shelf">
      <eLiterals name="Top"/>
      <eLiterals name="Bottom" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Section" eSuperTypes="#//Named">
      <eStructuralFeatures xsi:type="ecore:EReference" name="featured" eType="#//Book"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="shelf" eType="#//catalogue/Shelf"/>
    </eClassifiers>
    <eSubpackages name="archive" nsURI="http://example.org/fidelity/library/catalogue/archive" nsPrefix="arc">
      <eClassifiers xsi:type="ecore:EClass" name="Box">
        <eStructuralFeatures xsi:type="ecore:EReference" name="sections" upperBound="-1" eType="#//catalogue/Section"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
